Imports DevExpress.Mvvm.DataAnnotations
Imports Scaffolding.DatabaseFirst
Imports Scaffolding.DatabaseFirst.VB.Localization
Namespace Global.Scaffolding.DatabaseFirst.VB.NorthwindEntitiesDataModel
    Public Class NorthwindEntitiesMetadataProvider
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Category))
            builder.DisplayName(NorthwindEntitiesResources.Category)
            builder.[Property](Function(ByVal x) x.CategoryID).DisplayName(NorthwindEntitiesResources.Category_CategoryID)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Category_CategoryName)
            builder.[Property](Function(ByVal x) x.Description).DisplayName(NorthwindEntitiesResources.Category_Description)
            builder.[Property](Function(ByVal x) x.Picture).DisplayName(NorthwindEntitiesResources.Category_Picture)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of CustomerDemographic))
            builder.DisplayName(NorthwindEntitiesResources.CustomerDemographic)
            builder.[Property](Function(ByVal x) x.CustomerTypeID).DisplayName(NorthwindEntitiesResources.CustomerDemographic_CustomerTypeID)
            builder.[Property](Function(ByVal x) x.CustomerDesc).DisplayName(NorthwindEntitiesResources.CustomerDemographic_CustomerDesc)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Customer))
            builder.DisplayName(NorthwindEntitiesResources.Customer)
            builder.[Property](Function(ByVal x) x.CustomerID).DisplayName(NorthwindEntitiesResources.Customer_CustomerID)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Customer_CompanyName)
            builder.[Property](Function(ByVal x) x.ContactName).DisplayName(NorthwindEntitiesResources.Customer_ContactName)
            builder.[Property](Function(ByVal x) x.ContactTitle).DisplayName(NorthwindEntitiesResources.Customer_ContactTitle)
            builder.[Property](Function(ByVal x) x.Address).DisplayName(NorthwindEntitiesResources.Customer_Address)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Customer_City)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Customer_Region)
            builder.[Property](Function(ByVal x) x.PostalCode).DisplayName(NorthwindEntitiesResources.Customer_PostalCode)
            builder.[Property](Function(ByVal x) x.Country).DisplayName(NorthwindEntitiesResources.Customer_Country)
            builder.[Property](Function(ByVal x) x.Phone).DisplayName(NorthwindEntitiesResources.Customer_Phone)
            builder.[Property](Function(ByVal x) x.Fax).DisplayName(NorthwindEntitiesResources.Customer_Fax)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Employee))
            builder.DisplayName(NorthwindEntitiesResources.Employee)
            builder.[Property](Function(ByVal x) x.EmployeeID).DisplayName(NorthwindEntitiesResources.Employee_EmployeeID)
            builder.[Property](Function(ByVal x) x.LastName).DisplayName(NorthwindEntitiesResources.Employee_LastName)
            builder.[Property](Function(ByVal x) x.FirstName).DisplayName(NorthwindEntitiesResources.Employee_FirstName)
            builder.[Property](Function(ByVal x) x.Title).DisplayName(NorthwindEntitiesResources.Employee_Title)
            builder.[Property](Function(ByVal x) x.TitleOfCourtesy).DisplayName(NorthwindEntitiesResources.Employee_TitleOfCourtesy)
            builder.[Property](Function(ByVal x) x.BirthDate).DisplayName(NorthwindEntitiesResources.Employee_BirthDate)
            builder.[Property](Function(ByVal x) x.HireDate).DisplayName(NorthwindEntitiesResources.Employee_HireDate)
            builder.[Property](Function(ByVal x) x.Address).DisplayName(NorthwindEntitiesResources.Employee_Address)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Employee_City)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Employee_Region)
            builder.[Property](Function(ByVal x) x.PostalCode).DisplayName(NorthwindEntitiesResources.Employee_PostalCode)
            builder.[Property](Function(ByVal x) x.Country).DisplayName(NorthwindEntitiesResources.Employee_Country)
            builder.[Property](Function(ByVal x) x.HomePhone).DisplayName(NorthwindEntitiesResources.Employee_HomePhone)
            builder.[Property](Function(ByVal x) x.Extension).DisplayName(NorthwindEntitiesResources.Employee_Extension)
            builder.[Property](Function(ByVal x) x.Photo).DisplayName(NorthwindEntitiesResources.Employee_Photo)
            builder.[Property](Function(ByVal x) x.Notes).DisplayName(NorthwindEntitiesResources.Employee_Notes)
            builder.[Property](Function(ByVal x) x.PhotoPath).DisplayName(NorthwindEntitiesResources.Employee_PhotoPath)
            builder.[Property](Function(ByVal x) x.Employee1).DisplayName(NorthwindEntitiesResources.Employee_Employee1)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Order_Detail))
            builder.DisplayName(NorthwindEntitiesResources.Order_Detail)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Order_Detail_UnitPrice)
            builder.[Property](Function(ByVal x) x.Quantity).DisplayName(NorthwindEntitiesResources.Order_Detail_Quantity)
            builder.[Property](Function(ByVal x) x.Discount).DisplayName(NorthwindEntitiesResources.Order_Detail_Discount)
            builder.[Property](Function(ByVal x) x.Order).DisplayName(NorthwindEntitiesResources.Order_Detail_Order)
            builder.[Property](Function(ByVal x) x.Product).DisplayName(NorthwindEntitiesResources.Order_Detail_Product)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Order))
            builder.DisplayName(NorthwindEntitiesResources.Order)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Order_OrderID)
            builder.[Property](Function(ByVal x) x.OrderDate).DisplayName(NorthwindEntitiesResources.Order_OrderDate)
            builder.[Property](Function(ByVal x) x.RequiredDate).DisplayName(NorthwindEntitiesResources.Order_RequiredDate)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Order_ShippedDate)
            builder.[Property](Function(ByVal x) x.Freight).DisplayName(NorthwindEntitiesResources.Order_Freight)
            builder.[Property](Function(ByVal x) x.ShipName).DisplayName(NorthwindEntitiesResources.Order_ShipName)
            builder.[Property](Function(ByVal x) x.ShipAddress).DisplayName(NorthwindEntitiesResources.Order_ShipAddress)
            builder.[Property](Function(ByVal x) x.ShipCity).DisplayName(NorthwindEntitiesResources.Order_ShipCity)
            builder.[Property](Function(ByVal x) x.ShipRegion).DisplayName(NorthwindEntitiesResources.Order_ShipRegion)
            builder.[Property](Function(ByVal x) x.ShipPostalCode).DisplayName(NorthwindEntitiesResources.Order_ShipPostalCode)
            builder.[Property](Function(ByVal x) x.ShipCountry).DisplayName(NorthwindEntitiesResources.Order_ShipCountry)
            builder.[Property](Function(ByVal x) x.Customer).DisplayName(NorthwindEntitiesResources.Order_Customer)
            builder.[Property](Function(ByVal x) x.Employee).DisplayName(NorthwindEntitiesResources.Order_Employee)
            builder.[Property](Function(ByVal x) x.Shipper).DisplayName(NorthwindEntitiesResources.Order_Shipper)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Product))
            builder.DisplayName(NorthwindEntitiesResources.Product)
            builder.[Property](Function(ByVal x) x.ProductID).DisplayName(NorthwindEntitiesResources.Product_ProductID)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Product_ProductName)
            builder.[Property](Function(ByVal x) x.QuantityPerUnit).DisplayName(NorthwindEntitiesResources.Product_QuantityPerUnit)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Product_UnitPrice)
            builder.[Property](Function(ByVal x) x.UnitsInStock).DisplayName(NorthwindEntitiesResources.Product_UnitsInStock)
            builder.[Property](Function(ByVal x) x.UnitsOnOrder).DisplayName(NorthwindEntitiesResources.Product_UnitsOnOrder)
            builder.[Property](Function(ByVal x) x.ReorderLevel).DisplayName(NorthwindEntitiesResources.Product_ReorderLevel)
            builder.[Property](Function(ByVal x) x.Discontinued).DisplayName(NorthwindEntitiesResources.Product_Discontinued)
            builder.[Property](Function(ByVal x) x.Category).DisplayName(NorthwindEntitiesResources.Product_Category)
            builder.[Property](Function(ByVal x) x.Supplier).DisplayName(NorthwindEntitiesResources.Product_Supplier)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Region))
            builder.DisplayName(NorthwindEntitiesResources.Region)
            builder.[Property](Function(ByVal x) x.RegionID).DisplayName(NorthwindEntitiesResources.Region_RegionID)
            builder.[Property](Function(ByVal x) x.RegionDescription).DisplayName(NorthwindEntitiesResources.Region_RegionDescription)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Shipper))
            builder.DisplayName(NorthwindEntitiesResources.Shipper)
            builder.[Property](Function(ByVal x) x.ShipperID).DisplayName(NorthwindEntitiesResources.Shipper_ShipperID)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Shipper_CompanyName)
            builder.[Property](Function(ByVal x) x.Phone).DisplayName(NorthwindEntitiesResources.Shipper_Phone)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Supplier))
            builder.DisplayName(NorthwindEntitiesResources.Supplier)
            builder.[Property](Function(ByVal x) x.SupplierID).DisplayName(NorthwindEntitiesResources.Supplier_SupplierID)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Supplier_CompanyName)
            builder.[Property](Function(ByVal x) x.ContactName).DisplayName(NorthwindEntitiesResources.Supplier_ContactName)
            builder.[Property](Function(ByVal x) x.ContactTitle).DisplayName(NorthwindEntitiesResources.Supplier_ContactTitle)
            builder.[Property](Function(ByVal x) x.Address).DisplayName(NorthwindEntitiesResources.Supplier_Address)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Supplier_City)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Supplier_Region)
            builder.[Property](Function(ByVal x) x.PostalCode).DisplayName(NorthwindEntitiesResources.Supplier_PostalCode)
            builder.[Property](Function(ByVal x) x.Country).DisplayName(NorthwindEntitiesResources.Supplier_Country)
            builder.[Property](Function(ByVal x) x.Phone).DisplayName(NorthwindEntitiesResources.Supplier_Phone)
            builder.[Property](Function(ByVal x) x.Fax).DisplayName(NorthwindEntitiesResources.Supplier_Fax)
            builder.[Property](Function(ByVal x) x.HomePage).DisplayName(NorthwindEntitiesResources.Supplier_HomePage)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Territory))
            builder.DisplayName(NorthwindEntitiesResources.Territory)
            builder.[Property](Function(ByVal x) x.TerritoryID).DisplayName(NorthwindEntitiesResources.Territory_TerritoryID)
            builder.[Property](Function(ByVal x) x.TerritoryDescription).DisplayName(NorthwindEntitiesResources.Territory_TerritoryDescription)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Territory_Region)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Alphabetical_list_of_product))
            builder.DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product)
            builder.[Property](Function(ByVal x) x.ProductID).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_ProductID)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_ProductName)
            builder.[Property](Function(ByVal x) x.SupplierID).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_SupplierID)
            builder.[Property](Function(ByVal x) x.CategoryID).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_CategoryID)
            builder.[Property](Function(ByVal x) x.QuantityPerUnit).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_QuantityPerUnit)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_UnitPrice)
            builder.[Property](Function(ByVal x) x.UnitsInStock).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_UnitsInStock)
            builder.[Property](Function(ByVal x) x.UnitsOnOrder).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_UnitsOnOrder)
            builder.[Property](Function(ByVal x) x.ReorderLevel).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_ReorderLevel)
            builder.[Property](Function(ByVal x) x.Discontinued).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_Discontinued)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Alphabetical_list_of_product_CategoryName)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Category_Sales_for_1997))
            builder.DisplayName(NorthwindEntitiesResources.Category_Sales_for_1997)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Category_Sales_for_1997_CategoryName)
            builder.[Property](Function(ByVal x) x.CategorySales).DisplayName(NorthwindEntitiesResources.Category_Sales_for_1997_CategorySales)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Current_Product_List))
            builder.DisplayName(NorthwindEntitiesResources.Current_Product_List)
            builder.[Property](Function(ByVal x) x.ProductID).DisplayName(NorthwindEntitiesResources.Current_Product_List_ProductID)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Current_Product_List_ProductName)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Customer_and_Suppliers_by_City))
            builder.DisplayName(NorthwindEntitiesResources.Customer_and_Suppliers_by_City)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Customer_and_Suppliers_by_City_City)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Customer_and_Suppliers_by_City_CompanyName)
            builder.[Property](Function(ByVal x) x.ContactName).DisplayName(NorthwindEntitiesResources.Customer_and_Suppliers_by_City_ContactName)
            builder.[Property](Function(ByVal x) x.Relationship).DisplayName(NorthwindEntitiesResources.Customer_and_Suppliers_by_City_Relationship)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Invoice))
            builder.DisplayName(NorthwindEntitiesResources.Invoice)
            builder.[Property](Function(ByVal x) x.ShipName).DisplayName(NorthwindEntitiesResources.Invoice_ShipName)
            builder.[Property](Function(ByVal x) x.ShipAddress).DisplayName(NorthwindEntitiesResources.Invoice_ShipAddress)
            builder.[Property](Function(ByVal x) x.ShipCity).DisplayName(NorthwindEntitiesResources.Invoice_ShipCity)
            builder.[Property](Function(ByVal x) x.ShipRegion).DisplayName(NorthwindEntitiesResources.Invoice_ShipRegion)
            builder.[Property](Function(ByVal x) x.ShipPostalCode).DisplayName(NorthwindEntitiesResources.Invoice_ShipPostalCode)
            builder.[Property](Function(ByVal x) x.ShipCountry).DisplayName(NorthwindEntitiesResources.Invoice_ShipCountry)
            builder.[Property](Function(ByVal x) x.CustomerID).DisplayName(NorthwindEntitiesResources.Invoice_CustomerID)
            builder.[Property](Function(ByVal x) x.CustomerName).DisplayName(NorthwindEntitiesResources.Invoice_CustomerName)
            builder.[Property](Function(ByVal x) x.Address).DisplayName(NorthwindEntitiesResources.Invoice_Address)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Invoice_City)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Invoice_Region)
            builder.[Property](Function(ByVal x) x.PostalCode).DisplayName(NorthwindEntitiesResources.Invoice_PostalCode)
            builder.[Property](Function(ByVal x) x.Country).DisplayName(NorthwindEntitiesResources.Invoice_Country)
            builder.[Property](Function(ByVal x) x.Salesperson).DisplayName(NorthwindEntitiesResources.Invoice_Salesperson)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Invoice_OrderID)
            builder.[Property](Function(ByVal x) x.OrderDate).DisplayName(NorthwindEntitiesResources.Invoice_OrderDate)
            builder.[Property](Function(ByVal x) x.RequiredDate).DisplayName(NorthwindEntitiesResources.Invoice_RequiredDate)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Invoice_ShippedDate)
            builder.[Property](Function(ByVal x) x.ShipperName).DisplayName(NorthwindEntitiesResources.Invoice_ShipperName)
            builder.[Property](Function(ByVal x) x.ProductID).DisplayName(NorthwindEntitiesResources.Invoice_ProductID)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Invoice_ProductName)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Invoice_UnitPrice)
            builder.[Property](Function(ByVal x) x.Quantity).DisplayName(NorthwindEntitiesResources.Invoice_Quantity)
            builder.[Property](Function(ByVal x) x.Discount).DisplayName(NorthwindEntitiesResources.Invoice_Discount)
            builder.[Property](Function(ByVal x) x.ExtendedPrice).DisplayName(NorthwindEntitiesResources.Invoice_ExtendedPrice)
            builder.[Property](Function(ByVal x) x.Freight).DisplayName(NorthwindEntitiesResources.Invoice_Freight)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Order_Details_Extended))
            builder.DisplayName(NorthwindEntitiesResources.Order_Details_Extended)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_OrderID)
            builder.[Property](Function(ByVal x) x.ProductID).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_ProductID)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_ProductName)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_UnitPrice)
            builder.[Property](Function(ByVal x) x.Quantity).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_Quantity)
            builder.[Property](Function(ByVal x) x.Discount).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_Discount)
            builder.[Property](Function(ByVal x) x.ExtendedPrice).DisplayName(NorthwindEntitiesResources.Order_Details_Extended_ExtendedPrice)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Order_Subtotal))
            builder.DisplayName(NorthwindEntitiesResources.Order_Subtotal)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Order_Subtotal_OrderID)
            builder.[Property](Function(ByVal x) x.Subtotal).DisplayName(NorthwindEntitiesResources.Order_Subtotal_Subtotal)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Orders_Qry))
            builder.DisplayName(NorthwindEntitiesResources.Orders_Qry)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Orders_Qry_OrderID)
            builder.[Property](Function(ByVal x) x.CustomerID).DisplayName(NorthwindEntitiesResources.Orders_Qry_CustomerID)
            builder.[Property](Function(ByVal x) x.EmployeeID).DisplayName(NorthwindEntitiesResources.Orders_Qry_EmployeeID)
            builder.[Property](Function(ByVal x) x.OrderDate).DisplayName(NorthwindEntitiesResources.Orders_Qry_OrderDate)
            builder.[Property](Function(ByVal x) x.RequiredDate).DisplayName(NorthwindEntitiesResources.Orders_Qry_RequiredDate)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShippedDate)
            builder.[Property](Function(ByVal x) x.ShipVia).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipVia)
            builder.[Property](Function(ByVal x) x.Freight).DisplayName(NorthwindEntitiesResources.Orders_Qry_Freight)
            builder.[Property](Function(ByVal x) x.ShipName).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipName)
            builder.[Property](Function(ByVal x) x.ShipAddress).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipAddress)
            builder.[Property](Function(ByVal x) x.ShipCity).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipCity)
            builder.[Property](Function(ByVal x) x.ShipRegion).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipRegion)
            builder.[Property](Function(ByVal x) x.ShipPostalCode).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipPostalCode)
            builder.[Property](Function(ByVal x) x.ShipCountry).DisplayName(NorthwindEntitiesResources.Orders_Qry_ShipCountry)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Orders_Qry_CompanyName)
            builder.[Property](Function(ByVal x) x.Address).DisplayName(NorthwindEntitiesResources.Orders_Qry_Address)
            builder.[Property](Function(ByVal x) x.City).DisplayName(NorthwindEntitiesResources.Orders_Qry_City)
            builder.[Property](Function(ByVal x) x.Region).DisplayName(NorthwindEntitiesResources.Orders_Qry_Region)
            builder.[Property](Function(ByVal x) x.PostalCode).DisplayName(NorthwindEntitiesResources.Orders_Qry_PostalCode)
            builder.[Property](Function(ByVal x) x.Country).DisplayName(NorthwindEntitiesResources.Orders_Qry_Country)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Product_Sales_for_1997))
            builder.DisplayName(NorthwindEntitiesResources.Product_Sales_for_1997)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Product_Sales_for_1997_CategoryName)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Product_Sales_for_1997_ProductName)
            builder.[Property](Function(ByVal x) x.ProductSales).DisplayName(NorthwindEntitiesResources.Product_Sales_for_1997_ProductSales)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Products_Above_Average_Price))
            builder.DisplayName(NorthwindEntitiesResources.Products_Above_Average_Price)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Products_Above_Average_Price_ProductName)
            builder.[Property](Function(ByVal x) x.UnitPrice).DisplayName(NorthwindEntitiesResources.Products_Above_Average_Price_UnitPrice)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Products_by_Category))
            builder.DisplayName(NorthwindEntitiesResources.Products_by_Category)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Products_by_Category_CategoryName)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Products_by_Category_ProductName)
            builder.[Property](Function(ByVal x) x.QuantityPerUnit).DisplayName(NorthwindEntitiesResources.Products_by_Category_QuantityPerUnit)
            builder.[Property](Function(ByVal x) x.UnitsInStock).DisplayName(NorthwindEntitiesResources.Products_by_Category_UnitsInStock)
            builder.[Property](Function(ByVal x) x.Discontinued).DisplayName(NorthwindEntitiesResources.Products_by_Category_Discontinued)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Sales_by_Category))
            builder.DisplayName(NorthwindEntitiesResources.Sales_by_Category)
            builder.[Property](Function(ByVal x) x.CategoryID).DisplayName(NorthwindEntitiesResources.Sales_by_Category_CategoryID)
            builder.[Property](Function(ByVal x) x.CategoryName).DisplayName(NorthwindEntitiesResources.Sales_by_Category_CategoryName)
            builder.[Property](Function(ByVal x) x.ProductName).DisplayName(NorthwindEntitiesResources.Sales_by_Category_ProductName)
            builder.[Property](Function(ByVal x) x.ProductSales).DisplayName(NorthwindEntitiesResources.Sales_by_Category_ProductSales)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Sales_Totals_by_Amount))
            builder.DisplayName(NorthwindEntitiesResources.Sales_Totals_by_Amount)
            builder.[Property](Function(ByVal x) x.SaleAmount).DisplayName(NorthwindEntitiesResources.Sales_Totals_by_Amount_SaleAmount)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Sales_Totals_by_Amount_OrderID)
            builder.[Property](Function(ByVal x) x.CompanyName).DisplayName(NorthwindEntitiesResources.Sales_Totals_by_Amount_CompanyName)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Sales_Totals_by_Amount_ShippedDate)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Summary_of_Sales_by_Quarter))
            builder.DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Quarter)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Quarter_ShippedDate)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Quarter_OrderID)
            builder.[Property](Function(ByVal x) x.Subtotal).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Quarter_Subtotal)
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Summary_of_Sales_by_Year))
            builder.DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Year)
            builder.[Property](Function(ByVal x) x.ShippedDate).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Year_ShippedDate)
            builder.[Property](Function(ByVal x) x.OrderID).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Year_OrderID)
            builder.[Property](Function(ByVal x) x.Subtotal).DisplayName(NorthwindEntitiesResources.Summary_of_Sales_by_Year_Subtotal)
        End Sub
    End Class
End Namespace
