'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class NorthwindEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NorthwindEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property CustomerDemographics() As DbSet(Of CustomerDemographic)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property Order_Details() As DbSet(Of Order_Detail)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property Products() As DbSet(Of Product)
    Public Overridable Property Regions() As DbSet(Of Region)
    Public Overridable Property Shippers() As DbSet(Of Shipper)
    Public Overridable Property Suppliers() As DbSet(Of Supplier)
    Public Overridable Property Territories() As DbSet(Of Territory)
    Public Overridable Property Alphabetical_list_of_products() As DbSet(Of Alphabetical_list_of_product)
    Public Overridable Property Category_Sales_for_1997() As DbSet(Of Category_Sales_for_1997)
    Public Overridable Property Current_Product_Lists() As DbSet(Of Current_Product_List)
    Public Overridable Property Customer_and_Suppliers_by_Cities() As DbSet(Of Customer_and_Suppliers_by_City)
    Public Overridable Property Invoices() As DbSet(Of Invoice)
    Public Overridable Property Order_Details_Extendeds() As DbSet(Of Order_Details_Extended)
    Public Overridable Property Order_Subtotals() As DbSet(Of Order_Subtotal)
    Public Overridable Property Orders_Qries() As DbSet(Of Orders_Qry)
    Public Overridable Property Product_Sales_for_1997() As DbSet(Of Product_Sales_for_1997)
    Public Overridable Property Products_Above_Average_Prices() As DbSet(Of Products_Above_Average_Price)
    Public Overridable Property Products_by_Categories() As DbSet(Of Products_by_Category)
    Public Overridable Property Sales_by_Categories() As DbSet(Of Sales_by_Category)
    Public Overridable Property Sales_Totals_by_Amounts() As DbSet(Of Sales_Totals_by_Amount)
    Public Overridable Property Summary_of_Sales_by_Quarters() As DbSet(Of Summary_of_Sales_by_Quarter)
    Public Overridable Property Summary_of_Sales_by_Years() As DbSet(Of Summary_of_Sales_by_Year)

End Class
