//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding.DatabaseFirst.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NorthwindEntitiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NorthwindEntitiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scaffolding.DatabaseFirst.Resources.NorthwindEntitiesResources", typeof(NorthwindEntitiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

			        public static string Category { get { return ResourceManager.GetString("Category", resourceCulture); } }
		        public static string Category_Plural { get { return ResourceManager.GetString("Category_Plural", resourceCulture); } }
		        public static string Category_CategoryID { get { return ResourceManager.GetString("Category_CategoryID", resourceCulture); } }
		        public static string Category_CategoryName { get { return ResourceManager.GetString("Category_CategoryName", resourceCulture); } }
		        public static string Category_Description { get { return ResourceManager.GetString("Category_Description", resourceCulture); } }
		        public static string Category_Picture { get { return ResourceManager.GetString("Category_Picture", resourceCulture); } }
		        public static string CustomerDemographic { get { return ResourceManager.GetString("CustomerDemographic", resourceCulture); } }
		        public static string CustomerDemographic_Plural { get { return ResourceManager.GetString("CustomerDemographic_Plural", resourceCulture); } }
		        public static string CustomerDemographic_CustomerTypeID { get { return ResourceManager.GetString("CustomerDemographic_CustomerTypeID", resourceCulture); } }
		        public static string CustomerDemographic_CustomerDesc { get { return ResourceManager.GetString("CustomerDemographic_CustomerDesc", resourceCulture); } }
		        public static string Customer { get { return ResourceManager.GetString("Customer", resourceCulture); } }
		        public static string Customer_Plural { get { return ResourceManager.GetString("Customer_Plural", resourceCulture); } }
		        public static string Customer_CustomerID { get { return ResourceManager.GetString("Customer_CustomerID", resourceCulture); } }
		        public static string Customer_CompanyName { get { return ResourceManager.GetString("Customer_CompanyName", resourceCulture); } }
		        public static string Customer_ContactName { get { return ResourceManager.GetString("Customer_ContactName", resourceCulture); } }
		        public static string Customer_ContactTitle { get { return ResourceManager.GetString("Customer_ContactTitle", resourceCulture); } }
		        public static string Customer_Address { get { return ResourceManager.GetString("Customer_Address", resourceCulture); } }
		        public static string Customer_City { get { return ResourceManager.GetString("Customer_City", resourceCulture); } }
		        public static string Customer_Region { get { return ResourceManager.GetString("Customer_Region", resourceCulture); } }
		        public static string Customer_PostalCode { get { return ResourceManager.GetString("Customer_PostalCode", resourceCulture); } }
		        public static string Customer_Country { get { return ResourceManager.GetString("Customer_Country", resourceCulture); } }
		        public static string Customer_Phone { get { return ResourceManager.GetString("Customer_Phone", resourceCulture); } }
		        public static string Customer_Fax { get { return ResourceManager.GetString("Customer_Fax", resourceCulture); } }
		        public static string Employee { get { return ResourceManager.GetString("Employee", resourceCulture); } }
		        public static string Employee_Plural { get { return ResourceManager.GetString("Employee_Plural", resourceCulture); } }
		        public static string Employee_EmployeeID { get { return ResourceManager.GetString("Employee_EmployeeID", resourceCulture); } }
		        public static string Employee_LastName { get { return ResourceManager.GetString("Employee_LastName", resourceCulture); } }
		        public static string Employee_FirstName { get { return ResourceManager.GetString("Employee_FirstName", resourceCulture); } }
		        public static string Employee_Title { get { return ResourceManager.GetString("Employee_Title", resourceCulture); } }
		        public static string Employee_TitleOfCourtesy { get { return ResourceManager.GetString("Employee_TitleOfCourtesy", resourceCulture); } }
		        public static string Employee_BirthDate { get { return ResourceManager.GetString("Employee_BirthDate", resourceCulture); } }
		        public static string Employee_HireDate { get { return ResourceManager.GetString("Employee_HireDate", resourceCulture); } }
		        public static string Employee_Address { get { return ResourceManager.GetString("Employee_Address", resourceCulture); } }
		        public static string Employee_City { get { return ResourceManager.GetString("Employee_City", resourceCulture); } }
		        public static string Employee_Region { get { return ResourceManager.GetString("Employee_Region", resourceCulture); } }
		        public static string Employee_PostalCode { get { return ResourceManager.GetString("Employee_PostalCode", resourceCulture); } }
		        public static string Employee_Country { get { return ResourceManager.GetString("Employee_Country", resourceCulture); } }
		        public static string Employee_HomePhone { get { return ResourceManager.GetString("Employee_HomePhone", resourceCulture); } }
		        public static string Employee_Extension { get { return ResourceManager.GetString("Employee_Extension", resourceCulture); } }
		        public static string Employee_Photo { get { return ResourceManager.GetString("Employee_Photo", resourceCulture); } }
		        public static string Employee_Notes { get { return ResourceManager.GetString("Employee_Notes", resourceCulture); } }
		        public static string Employee_PhotoPath { get { return ResourceManager.GetString("Employee_PhotoPath", resourceCulture); } }
		        public static string Employee_Employee1 { get { return ResourceManager.GetString("Employee_Employee1", resourceCulture); } }
		        public static string Order_Detail { get { return ResourceManager.GetString("Order_Detail", resourceCulture); } }
		        public static string Order_Detail_Plural { get { return ResourceManager.GetString("Order_Detail_Plural", resourceCulture); } }
		        public static string Order_Detail_UnitPrice { get { return ResourceManager.GetString("Order_Detail_UnitPrice", resourceCulture); } }
		        public static string Order_Detail_Quantity { get { return ResourceManager.GetString("Order_Detail_Quantity", resourceCulture); } }
		        public static string Order_Detail_Discount { get { return ResourceManager.GetString("Order_Detail_Discount", resourceCulture); } }
		        public static string Order_Detail_Order { get { return ResourceManager.GetString("Order_Detail_Order", resourceCulture); } }
		        public static string Order_Detail_Product { get { return ResourceManager.GetString("Order_Detail_Product", resourceCulture); } }
		        public static string Order { get { return ResourceManager.GetString("Order", resourceCulture); } }
		        public static string Order_Plural { get { return ResourceManager.GetString("Order_Plural", resourceCulture); } }
		        public static string Order_OrderID { get { return ResourceManager.GetString("Order_OrderID", resourceCulture); } }
		        public static string Order_OrderDate { get { return ResourceManager.GetString("Order_OrderDate", resourceCulture); } }
		        public static string Order_RequiredDate { get { return ResourceManager.GetString("Order_RequiredDate", resourceCulture); } }
		        public static string Order_ShippedDate { get { return ResourceManager.GetString("Order_ShippedDate", resourceCulture); } }
		        public static string Order_Freight { get { return ResourceManager.GetString("Order_Freight", resourceCulture); } }
		        public static string Order_ShipName { get { return ResourceManager.GetString("Order_ShipName", resourceCulture); } }
		        public static string Order_ShipAddress { get { return ResourceManager.GetString("Order_ShipAddress", resourceCulture); } }
		        public static string Order_ShipCity { get { return ResourceManager.GetString("Order_ShipCity", resourceCulture); } }
		        public static string Order_ShipRegion { get { return ResourceManager.GetString("Order_ShipRegion", resourceCulture); } }
		        public static string Order_ShipPostalCode { get { return ResourceManager.GetString("Order_ShipPostalCode", resourceCulture); } }
		        public static string Order_ShipCountry { get { return ResourceManager.GetString("Order_ShipCountry", resourceCulture); } }
		        public static string Order_Customer { get { return ResourceManager.GetString("Order_Customer", resourceCulture); } }
		        public static string Order_Employee { get { return ResourceManager.GetString("Order_Employee", resourceCulture); } }
		        public static string Order_Shipper { get { return ResourceManager.GetString("Order_Shipper", resourceCulture); } }
		        public static string Product { get { return ResourceManager.GetString("Product", resourceCulture); } }
		        public static string Product_Plural { get { return ResourceManager.GetString("Product_Plural", resourceCulture); } }
		        public static string Product_ProductID { get { return ResourceManager.GetString("Product_ProductID", resourceCulture); } }
		        public static string Product_ProductName { get { return ResourceManager.GetString("Product_ProductName", resourceCulture); } }
		        public static string Product_QuantityPerUnit { get { return ResourceManager.GetString("Product_QuantityPerUnit", resourceCulture); } }
		        public static string Product_UnitPrice { get { return ResourceManager.GetString("Product_UnitPrice", resourceCulture); } }
		        public static string Product_UnitsInStock { get { return ResourceManager.GetString("Product_UnitsInStock", resourceCulture); } }
		        public static string Product_UnitsOnOrder { get { return ResourceManager.GetString("Product_UnitsOnOrder", resourceCulture); } }
		        public static string Product_ReorderLevel { get { return ResourceManager.GetString("Product_ReorderLevel", resourceCulture); } }
		        public static string Product_Discontinued { get { return ResourceManager.GetString("Product_Discontinued", resourceCulture); } }
		        public static string Product_Category { get { return ResourceManager.GetString("Product_Category", resourceCulture); } }
		        public static string Product_Supplier { get { return ResourceManager.GetString("Product_Supplier", resourceCulture); } }
		        public static string Region { get { return ResourceManager.GetString("Region", resourceCulture); } }
		        public static string Region_Plural { get { return ResourceManager.GetString("Region_Plural", resourceCulture); } }
		        public static string Region_RegionID { get { return ResourceManager.GetString("Region_RegionID", resourceCulture); } }
		        public static string Region_RegionDescription { get { return ResourceManager.GetString("Region_RegionDescription", resourceCulture); } }
		        public static string Shipper { get { return ResourceManager.GetString("Shipper", resourceCulture); } }
		        public static string Shipper_Plural { get { return ResourceManager.GetString("Shipper_Plural", resourceCulture); } }
		        public static string Shipper_ShipperID { get { return ResourceManager.GetString("Shipper_ShipperID", resourceCulture); } }
		        public static string Shipper_CompanyName { get { return ResourceManager.GetString("Shipper_CompanyName", resourceCulture); } }
		        public static string Shipper_Phone { get { return ResourceManager.GetString("Shipper_Phone", resourceCulture); } }
		        public static string Supplier { get { return ResourceManager.GetString("Supplier", resourceCulture); } }
		        public static string Supplier_Plural { get { return ResourceManager.GetString("Supplier_Plural", resourceCulture); } }
		        public static string Supplier_SupplierID { get { return ResourceManager.GetString("Supplier_SupplierID", resourceCulture); } }
		        public static string Supplier_CompanyName { get { return ResourceManager.GetString("Supplier_CompanyName", resourceCulture); } }
		        public static string Supplier_ContactName { get { return ResourceManager.GetString("Supplier_ContactName", resourceCulture); } }
		        public static string Supplier_ContactTitle { get { return ResourceManager.GetString("Supplier_ContactTitle", resourceCulture); } }
		        public static string Supplier_Address { get { return ResourceManager.GetString("Supplier_Address", resourceCulture); } }
		        public static string Supplier_City { get { return ResourceManager.GetString("Supplier_City", resourceCulture); } }
		        public static string Supplier_Region { get { return ResourceManager.GetString("Supplier_Region", resourceCulture); } }
		        public static string Supplier_PostalCode { get { return ResourceManager.GetString("Supplier_PostalCode", resourceCulture); } }
		        public static string Supplier_Country { get { return ResourceManager.GetString("Supplier_Country", resourceCulture); } }
		        public static string Supplier_Phone { get { return ResourceManager.GetString("Supplier_Phone", resourceCulture); } }
		        public static string Supplier_Fax { get { return ResourceManager.GetString("Supplier_Fax", resourceCulture); } }
		        public static string Supplier_HomePage { get { return ResourceManager.GetString("Supplier_HomePage", resourceCulture); } }
		        public static string Territory { get { return ResourceManager.GetString("Territory", resourceCulture); } }
		        public static string Territory_Plural { get { return ResourceManager.GetString("Territory_Plural", resourceCulture); } }
		        public static string Territory_TerritoryID { get { return ResourceManager.GetString("Territory_TerritoryID", resourceCulture); } }
		        public static string Territory_TerritoryDescription { get { return ResourceManager.GetString("Territory_TerritoryDescription", resourceCulture); } }
		        public static string Territory_Region { get { return ResourceManager.GetString("Territory_Region", resourceCulture); } }
		        public static string Alphabetical_list_of_product { get { return ResourceManager.GetString("Alphabetical_list_of_product", resourceCulture); } }
		        public static string Alphabetical_list_of_product_Plural { get { return ResourceManager.GetString("Alphabetical_list_of_product_Plural", resourceCulture); } }
		        public static string Alphabetical_list_of_product_ProductID { get { return ResourceManager.GetString("Alphabetical_list_of_product_ProductID", resourceCulture); } }
		        public static string Alphabetical_list_of_product_ProductName { get { return ResourceManager.GetString("Alphabetical_list_of_product_ProductName", resourceCulture); } }
		        public static string Alphabetical_list_of_product_SupplierID { get { return ResourceManager.GetString("Alphabetical_list_of_product_SupplierID", resourceCulture); } }
		        public static string Alphabetical_list_of_product_CategoryID { get { return ResourceManager.GetString("Alphabetical_list_of_product_CategoryID", resourceCulture); } }
		        public static string Alphabetical_list_of_product_QuantityPerUnit { get { return ResourceManager.GetString("Alphabetical_list_of_product_QuantityPerUnit", resourceCulture); } }
		        public static string Alphabetical_list_of_product_UnitPrice { get { return ResourceManager.GetString("Alphabetical_list_of_product_UnitPrice", resourceCulture); } }
		        public static string Alphabetical_list_of_product_UnitsInStock { get { return ResourceManager.GetString("Alphabetical_list_of_product_UnitsInStock", resourceCulture); } }
		        public static string Alphabetical_list_of_product_UnitsOnOrder { get { return ResourceManager.GetString("Alphabetical_list_of_product_UnitsOnOrder", resourceCulture); } }
		        public static string Alphabetical_list_of_product_ReorderLevel { get { return ResourceManager.GetString("Alphabetical_list_of_product_ReorderLevel", resourceCulture); } }
		        public static string Alphabetical_list_of_product_Discontinued { get { return ResourceManager.GetString("Alphabetical_list_of_product_Discontinued", resourceCulture); } }
		        public static string Alphabetical_list_of_product_CategoryName { get { return ResourceManager.GetString("Alphabetical_list_of_product_CategoryName", resourceCulture); } }
		        public static string Category_Sales_for_1997 { get { return ResourceManager.GetString("Category_Sales_for_1997", resourceCulture); } }
		        public static string Category_Sales_for_1997_Plural { get { return ResourceManager.GetString("Category_Sales_for_1997_Plural", resourceCulture); } }
		        public static string Category_Sales_for_1997_CategoryName { get { return ResourceManager.GetString("Category_Sales_for_1997_CategoryName", resourceCulture); } }
		        public static string Category_Sales_for_1997_CategorySales { get { return ResourceManager.GetString("Category_Sales_for_1997_CategorySales", resourceCulture); } }
		        public static string Current_Product_List { get { return ResourceManager.GetString("Current_Product_List", resourceCulture); } }
		        public static string Current_Product_List_Plural { get { return ResourceManager.GetString("Current_Product_List_Plural", resourceCulture); } }
		        public static string Current_Product_List_ProductID { get { return ResourceManager.GetString("Current_Product_List_ProductID", resourceCulture); } }
		        public static string Current_Product_List_ProductName { get { return ResourceManager.GetString("Current_Product_List_ProductName", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City_Plural { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City_Plural", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City_City { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City_City", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City_CompanyName { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City_CompanyName", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City_ContactName { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City_ContactName", resourceCulture); } }
		        public static string Customer_and_Suppliers_by_City_Relationship { get { return ResourceManager.GetString("Customer_and_Suppliers_by_City_Relationship", resourceCulture); } }
		        public static string Invoice { get { return ResourceManager.GetString("Invoice", resourceCulture); } }
		        public static string Invoice_Plural { get { return ResourceManager.GetString("Invoice_Plural", resourceCulture); } }
		        public static string Invoice_ShipName { get { return ResourceManager.GetString("Invoice_ShipName", resourceCulture); } }
		        public static string Invoice_ShipAddress { get { return ResourceManager.GetString("Invoice_ShipAddress", resourceCulture); } }
		        public static string Invoice_ShipCity { get { return ResourceManager.GetString("Invoice_ShipCity", resourceCulture); } }
		        public static string Invoice_ShipRegion { get { return ResourceManager.GetString("Invoice_ShipRegion", resourceCulture); } }
		        public static string Invoice_ShipPostalCode { get { return ResourceManager.GetString("Invoice_ShipPostalCode", resourceCulture); } }
		        public static string Invoice_ShipCountry { get { return ResourceManager.GetString("Invoice_ShipCountry", resourceCulture); } }
		        public static string Invoice_CustomerID { get { return ResourceManager.GetString("Invoice_CustomerID", resourceCulture); } }
		        public static string Invoice_CustomerName { get { return ResourceManager.GetString("Invoice_CustomerName", resourceCulture); } }
		        public static string Invoice_Address { get { return ResourceManager.GetString("Invoice_Address", resourceCulture); } }
		        public static string Invoice_City { get { return ResourceManager.GetString("Invoice_City", resourceCulture); } }
		        public static string Invoice_Region { get { return ResourceManager.GetString("Invoice_Region", resourceCulture); } }
		        public static string Invoice_PostalCode { get { return ResourceManager.GetString("Invoice_PostalCode", resourceCulture); } }
		        public static string Invoice_Country { get { return ResourceManager.GetString("Invoice_Country", resourceCulture); } }
		        public static string Invoice_Salesperson { get { return ResourceManager.GetString("Invoice_Salesperson", resourceCulture); } }
		        public static string Invoice_OrderID { get { return ResourceManager.GetString("Invoice_OrderID", resourceCulture); } }
		        public static string Invoice_OrderDate { get { return ResourceManager.GetString("Invoice_OrderDate", resourceCulture); } }
		        public static string Invoice_RequiredDate { get { return ResourceManager.GetString("Invoice_RequiredDate", resourceCulture); } }
		        public static string Invoice_ShippedDate { get { return ResourceManager.GetString("Invoice_ShippedDate", resourceCulture); } }
		        public static string Invoice_ShipperName { get { return ResourceManager.GetString("Invoice_ShipperName", resourceCulture); } }
		        public static string Invoice_ProductID { get { return ResourceManager.GetString("Invoice_ProductID", resourceCulture); } }
		        public static string Invoice_ProductName { get { return ResourceManager.GetString("Invoice_ProductName", resourceCulture); } }
		        public static string Invoice_UnitPrice { get { return ResourceManager.GetString("Invoice_UnitPrice", resourceCulture); } }
		        public static string Invoice_Quantity { get { return ResourceManager.GetString("Invoice_Quantity", resourceCulture); } }
		        public static string Invoice_Discount { get { return ResourceManager.GetString("Invoice_Discount", resourceCulture); } }
		        public static string Invoice_ExtendedPrice { get { return ResourceManager.GetString("Invoice_ExtendedPrice", resourceCulture); } }
		        public static string Invoice_Freight { get { return ResourceManager.GetString("Invoice_Freight", resourceCulture); } }
		        public static string Order_Details_Extended { get { return ResourceManager.GetString("Order_Details_Extended", resourceCulture); } }
		        public static string Order_Details_Extended_Plural { get { return ResourceManager.GetString("Order_Details_Extended_Plural", resourceCulture); } }
		        public static string Order_Details_Extended_OrderID { get { return ResourceManager.GetString("Order_Details_Extended_OrderID", resourceCulture); } }
		        public static string Order_Details_Extended_ProductID { get { return ResourceManager.GetString("Order_Details_Extended_ProductID", resourceCulture); } }
		        public static string Order_Details_Extended_ProductName { get { return ResourceManager.GetString("Order_Details_Extended_ProductName", resourceCulture); } }
		        public static string Order_Details_Extended_UnitPrice { get { return ResourceManager.GetString("Order_Details_Extended_UnitPrice", resourceCulture); } }
		        public static string Order_Details_Extended_Quantity { get { return ResourceManager.GetString("Order_Details_Extended_Quantity", resourceCulture); } }
		        public static string Order_Details_Extended_Discount { get { return ResourceManager.GetString("Order_Details_Extended_Discount", resourceCulture); } }
		        public static string Order_Details_Extended_ExtendedPrice { get { return ResourceManager.GetString("Order_Details_Extended_ExtendedPrice", resourceCulture); } }
		        public static string Order_Subtotal { get { return ResourceManager.GetString("Order_Subtotal", resourceCulture); } }
		        public static string Order_Subtotal_Plural { get { return ResourceManager.GetString("Order_Subtotal_Plural", resourceCulture); } }
		        public static string Order_Subtotal_OrderID { get { return ResourceManager.GetString("Order_Subtotal_OrderID", resourceCulture); } }
		        public static string Order_Subtotal_Subtotal { get { return ResourceManager.GetString("Order_Subtotal_Subtotal", resourceCulture); } }
		        public static string Orders_Qry { get { return ResourceManager.GetString("Orders_Qry", resourceCulture); } }
		        public static string Orders_Qry_Plural { get { return ResourceManager.GetString("Orders_Qry_Plural", resourceCulture); } }
		        public static string Orders_Qry_OrderID { get { return ResourceManager.GetString("Orders_Qry_OrderID", resourceCulture); } }
		        public static string Orders_Qry_CustomerID { get { return ResourceManager.GetString("Orders_Qry_CustomerID", resourceCulture); } }
		        public static string Orders_Qry_EmployeeID { get { return ResourceManager.GetString("Orders_Qry_EmployeeID", resourceCulture); } }
		        public static string Orders_Qry_OrderDate { get { return ResourceManager.GetString("Orders_Qry_OrderDate", resourceCulture); } }
		        public static string Orders_Qry_RequiredDate { get { return ResourceManager.GetString("Orders_Qry_RequiredDate", resourceCulture); } }
		        public static string Orders_Qry_ShippedDate { get { return ResourceManager.GetString("Orders_Qry_ShippedDate", resourceCulture); } }
		        public static string Orders_Qry_ShipVia { get { return ResourceManager.GetString("Orders_Qry_ShipVia", resourceCulture); } }
		        public static string Orders_Qry_Freight { get { return ResourceManager.GetString("Orders_Qry_Freight", resourceCulture); } }
		        public static string Orders_Qry_ShipName { get { return ResourceManager.GetString("Orders_Qry_ShipName", resourceCulture); } }
		        public static string Orders_Qry_ShipAddress { get { return ResourceManager.GetString("Orders_Qry_ShipAddress", resourceCulture); } }
		        public static string Orders_Qry_ShipCity { get { return ResourceManager.GetString("Orders_Qry_ShipCity", resourceCulture); } }
		        public static string Orders_Qry_ShipRegion { get { return ResourceManager.GetString("Orders_Qry_ShipRegion", resourceCulture); } }
		        public static string Orders_Qry_ShipPostalCode { get { return ResourceManager.GetString("Orders_Qry_ShipPostalCode", resourceCulture); } }
		        public static string Orders_Qry_ShipCountry { get { return ResourceManager.GetString("Orders_Qry_ShipCountry", resourceCulture); } }
		        public static string Orders_Qry_CompanyName { get { return ResourceManager.GetString("Orders_Qry_CompanyName", resourceCulture); } }
		        public static string Orders_Qry_Address { get { return ResourceManager.GetString("Orders_Qry_Address", resourceCulture); } }
		        public static string Orders_Qry_City { get { return ResourceManager.GetString("Orders_Qry_City", resourceCulture); } }
		        public static string Orders_Qry_Region { get { return ResourceManager.GetString("Orders_Qry_Region", resourceCulture); } }
		        public static string Orders_Qry_PostalCode { get { return ResourceManager.GetString("Orders_Qry_PostalCode", resourceCulture); } }
		        public static string Orders_Qry_Country { get { return ResourceManager.GetString("Orders_Qry_Country", resourceCulture); } }
		        public static string Product_Sales_for_1997 { get { return ResourceManager.GetString("Product_Sales_for_1997", resourceCulture); } }
		        public static string Product_Sales_for_1997_Plural { get { return ResourceManager.GetString("Product_Sales_for_1997_Plural", resourceCulture); } }
		        public static string Product_Sales_for_1997_CategoryName { get { return ResourceManager.GetString("Product_Sales_for_1997_CategoryName", resourceCulture); } }
		        public static string Product_Sales_for_1997_ProductName { get { return ResourceManager.GetString("Product_Sales_for_1997_ProductName", resourceCulture); } }
		        public static string Product_Sales_for_1997_ProductSales { get { return ResourceManager.GetString("Product_Sales_for_1997_ProductSales", resourceCulture); } }
		        public static string Products_Above_Average_Price { get { return ResourceManager.GetString("Products_Above_Average_Price", resourceCulture); } }
		        public static string Products_Above_Average_Price_Plural { get { return ResourceManager.GetString("Products_Above_Average_Price_Plural", resourceCulture); } }
		        public static string Products_Above_Average_Price_ProductName { get { return ResourceManager.GetString("Products_Above_Average_Price_ProductName", resourceCulture); } }
		        public static string Products_Above_Average_Price_UnitPrice { get { return ResourceManager.GetString("Products_Above_Average_Price_UnitPrice", resourceCulture); } }
		        public static string Products_by_Category { get { return ResourceManager.GetString("Products_by_Category", resourceCulture); } }
		        public static string Products_by_Category_Plural { get { return ResourceManager.GetString("Products_by_Category_Plural", resourceCulture); } }
		        public static string Products_by_Category_CategoryName { get { return ResourceManager.GetString("Products_by_Category_CategoryName", resourceCulture); } }
		        public static string Products_by_Category_ProductName { get { return ResourceManager.GetString("Products_by_Category_ProductName", resourceCulture); } }
		        public static string Products_by_Category_QuantityPerUnit { get { return ResourceManager.GetString("Products_by_Category_QuantityPerUnit", resourceCulture); } }
		        public static string Products_by_Category_UnitsInStock { get { return ResourceManager.GetString("Products_by_Category_UnitsInStock", resourceCulture); } }
		        public static string Products_by_Category_Discontinued { get { return ResourceManager.GetString("Products_by_Category_Discontinued", resourceCulture); } }
		        public static string Sales_by_Category { get { return ResourceManager.GetString("Sales_by_Category", resourceCulture); } }
		        public static string Sales_by_Category_Plural { get { return ResourceManager.GetString("Sales_by_Category_Plural", resourceCulture); } }
		        public static string Sales_by_Category_CategoryID { get { return ResourceManager.GetString("Sales_by_Category_CategoryID", resourceCulture); } }
		        public static string Sales_by_Category_CategoryName { get { return ResourceManager.GetString("Sales_by_Category_CategoryName", resourceCulture); } }
		        public static string Sales_by_Category_ProductName { get { return ResourceManager.GetString("Sales_by_Category_ProductName", resourceCulture); } }
		        public static string Sales_by_Category_ProductSales { get { return ResourceManager.GetString("Sales_by_Category_ProductSales", resourceCulture); } }
		        public static string Sales_Totals_by_Amount { get { return ResourceManager.GetString("Sales_Totals_by_Amount", resourceCulture); } }
		        public static string Sales_Totals_by_Amount_Plural { get { return ResourceManager.GetString("Sales_Totals_by_Amount_Plural", resourceCulture); } }
		        public static string Sales_Totals_by_Amount_SaleAmount { get { return ResourceManager.GetString("Sales_Totals_by_Amount_SaleAmount", resourceCulture); } }
		        public static string Sales_Totals_by_Amount_OrderID { get { return ResourceManager.GetString("Sales_Totals_by_Amount_OrderID", resourceCulture); } }
		        public static string Sales_Totals_by_Amount_CompanyName { get { return ResourceManager.GetString("Sales_Totals_by_Amount_CompanyName", resourceCulture); } }
		        public static string Sales_Totals_by_Amount_ShippedDate { get { return ResourceManager.GetString("Sales_Totals_by_Amount_ShippedDate", resourceCulture); } }
		        public static string Summary_of_Sales_by_Quarter { get { return ResourceManager.GetString("Summary_of_Sales_by_Quarter", resourceCulture); } }
		        public static string Summary_of_Sales_by_Quarter_Plural { get { return ResourceManager.GetString("Summary_of_Sales_by_Quarter_Plural", resourceCulture); } }
		        public static string Summary_of_Sales_by_Quarter_ShippedDate { get { return ResourceManager.GetString("Summary_of_Sales_by_Quarter_ShippedDate", resourceCulture); } }
		        public static string Summary_of_Sales_by_Quarter_OrderID { get { return ResourceManager.GetString("Summary_of_Sales_by_Quarter_OrderID", resourceCulture); } }
		        public static string Summary_of_Sales_by_Quarter_Subtotal { get { return ResourceManager.GetString("Summary_of_Sales_by_Quarter_Subtotal", resourceCulture); } }
		        public static string Summary_of_Sales_by_Year { get { return ResourceManager.GetString("Summary_of_Sales_by_Year", resourceCulture); } }
		        public static string Summary_of_Sales_by_Year_Plural { get { return ResourceManager.GetString("Summary_of_Sales_by_Year_Plural", resourceCulture); } }
		        public static string Summary_of_Sales_by_Year_ShippedDate { get { return ResourceManager.GetString("Summary_of_Sales_by_Year_ShippedDate", resourceCulture); } }
		        public static string Summary_of_Sales_by_Year_OrderID { get { return ResourceManager.GetString("Summary_of_Sales_by_Year_OrderID", resourceCulture); } }
		        public static string Summary_of_Sales_by_Year_Subtotal { get { return ResourceManager.GetString("Summary_of_Sales_by_Year_Subtotal", resourceCulture); } }
	
    }
}

