//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding.DatabaseFirst.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scaffolding.DatabaseFirst.Resources.ViewResources", typeof(ViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

			        public static string Command_New { get { return ResourceManager.GetString("Command_New", resourceCulture); } }
		        public static string Command_Edit { get { return ResourceManager.GetString("Command_Edit", resourceCulture); } }
		        public static string Command_Delete { get { return ResourceManager.GetString("Command_Delete", resourceCulture); } }
		        public static string Command_Refresh { get { return ResourceManager.GetString("Command_Refresh", resourceCulture); } }
		        public static string Command_Reports { get { return ResourceManager.GetString("Command_Reports", resourceCulture); } }
		        public static string Command_Add { get { return ResourceManager.GetString("Command_Add", resourceCulture); } }
		        public static string Command_Save { get { return ResourceManager.GetString("Command_Save", resourceCulture); } }
		        public static string Command_SaveAndClose { get { return ResourceManager.GetString("Command_SaveAndClose", resourceCulture); } }
		        public static string Command_SaveAndNew { get { return ResourceManager.GetString("Command_SaveAndNew", resourceCulture); } }
		        public static string Command_Reset { get { return ResourceManager.GetString("Command_Reset", resourceCulture); } }
		        public static string Command_SaveAll { get { return ResourceManager.GetString("Command_SaveAll", resourceCulture); } }
		        public static string Command_Close { get { return ResourceManager.GetString("Command_Close", resourceCulture); } }
		        public static string Command_Count { get { return ResourceManager.GetString("Command_Count", resourceCulture); } }
		        public static string Command_CustomizeLayout { get { return ResourceManager.GetString("Command_CustomizeLayout", resourceCulture); } }
		        public static string Command_SaveLayout { get { return ResourceManager.GetString("Command_SaveLayout", resourceCulture); } }
		        public static string Command_ResetLayout { get { return ResourceManager.GetString("Command_ResetLayout", resourceCulture); } }
		        public static string RibbonPage_Home { get { return ResourceManager.GetString("RibbonPage_Home", resourceCulture); } }
		        public static string RibbonPage_View { get { return ResourceManager.GetString("RibbonPage_View", resourceCulture); } }
		        public static string RibbonPageGroup_Tasks { get { return ResourceManager.GetString("RibbonPageGroup_Tasks", resourceCulture); } }
		        public static string RibbonPageGroup_Layout { get { return ResourceManager.GetString("RibbonPageGroup_Layout", resourceCulture); } }
		        public static string RibbonPageGroup_Appearance { get { return ResourceManager.GetString("RibbonPageGroup_Appearance", resourceCulture); } }
		        public static string LayoutPanel_Navigation { get { return ResourceManager.GetString("LayoutPanel_Navigation", resourceCulture); } }
	
    }
}

