'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Public Class NorthwindEntitiesResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scaffolding.DatabaseFirst.VB.NorthwindEntitiesResources", GetType(NorthwindEntitiesResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

					Public Shared ReadOnly Property Category() As String
            Get
                Return ResourceManager.GetString("Category", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CategoryPlural() As String
            Get
                Return ResourceManager.GetString("CategoryPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_CategoryID() As String
            Get
                Return ResourceManager.GetString("Category_CategoryID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_CategoryName() As String
            Get
                Return ResourceManager.GetString("Category_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Description() As String
            Get
                Return ResourceManager.GetString("Category_Description", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Picture() As String
            Get
                Return ResourceManager.GetString("Category_Picture", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CustomerDemographic() As String
            Get
                Return ResourceManager.GetString("CustomerDemographic", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CustomerDemographicPlural() As String
            Get
                Return ResourceManager.GetString("CustomerDemographicPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CustomerDemographic_CustomerTypeID() As String
            Get
                Return ResourceManager.GetString("CustomerDemographic_CustomerTypeID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CustomerDemographic_CustomerDesc() As String
            Get
                Return ResourceManager.GetString("CustomerDemographic_CustomerDesc", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer() As String
            Get
                Return ResourceManager.GetString("Customer", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property CustomerPlural() As String
            Get
                Return ResourceManager.GetString("CustomerPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_CustomerID() As String
            Get
                Return ResourceManager.GetString("Customer_CustomerID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_CompanyName() As String
            Get
                Return ResourceManager.GetString("Customer_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_ContactName() As String
            Get
                Return ResourceManager.GetString("Customer_ContactName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_ContactTitle() As String
            Get
                Return ResourceManager.GetString("Customer_ContactTitle", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_Address() As String
            Get
                Return ResourceManager.GetString("Customer_Address", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_City() As String
            Get
                Return ResourceManager.GetString("Customer_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_Region() As String
            Get
                Return ResourceManager.GetString("Customer_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_PostalCode() As String
            Get
                Return ResourceManager.GetString("Customer_PostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_Country() As String
            Get
                Return ResourceManager.GetString("Customer_Country", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_Phone() As String
            Get
                Return ResourceManager.GetString("Customer_Phone", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_Fax() As String
            Get
                Return ResourceManager.GetString("Customer_Fax", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee() As String
            Get
                Return ResourceManager.GetString("Employee", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property EmployeePlural() As String
            Get
                Return ResourceManager.GetString("EmployeePlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_EmployeeID() As String
            Get
                Return ResourceManager.GetString("Employee_EmployeeID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_LastName() As String
            Get
                Return ResourceManager.GetString("Employee_LastName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_FirstName() As String
            Get
                Return ResourceManager.GetString("Employee_FirstName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Title() As String
            Get
                Return ResourceManager.GetString("Employee_Title", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_TitleOfCourtesy() As String
            Get
                Return ResourceManager.GetString("Employee_TitleOfCourtesy", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_BirthDate() As String
            Get
                Return ResourceManager.GetString("Employee_BirthDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_HireDate() As String
            Get
                Return ResourceManager.GetString("Employee_HireDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Address() As String
            Get
                Return ResourceManager.GetString("Employee_Address", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_City() As String
            Get
                Return ResourceManager.GetString("Employee_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Region() As String
            Get
                Return ResourceManager.GetString("Employee_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_PostalCode() As String
            Get
                Return ResourceManager.GetString("Employee_PostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Country() As String
            Get
                Return ResourceManager.GetString("Employee_Country", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_HomePhone() As String
            Get
                Return ResourceManager.GetString("Employee_HomePhone", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Extension() As String
            Get
                Return ResourceManager.GetString("Employee_Extension", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Photo() As String
            Get
                Return ResourceManager.GetString("Employee_Photo", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Notes() As String
            Get
                Return ResourceManager.GetString("Employee_Notes", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_PhotoPath() As String
            Get
                Return ResourceManager.GetString("Employee_PhotoPath", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Employee_Employee1() As String
            Get
                Return ResourceManager.GetString("Employee_Employee1", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail() As String
            Get
                Return ResourceManager.GetString("Order_Detail", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_DetailPlural() As String
            Get
                Return ResourceManager.GetString("Order_DetailPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Order_Detail_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail_Quantity() As String
            Get
                Return ResourceManager.GetString("Order_Detail_Quantity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail_Discount() As String
            Get
                Return ResourceManager.GetString("Order_Detail_Discount", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail_Order() As String
            Get
                Return ResourceManager.GetString("Order_Detail_Order", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Detail_Product() As String
            Get
                Return ResourceManager.GetString("Order_Detail_Product", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order() As String
            Get
                Return ResourceManager.GetString("Order", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property OrderPlural() As String
            Get
                Return ResourceManager.GetString("OrderPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_OrderID() As String
            Get
                Return ResourceManager.GetString("Order_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_OrderDate() As String
            Get
                Return ResourceManager.GetString("Order_OrderDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_RequiredDate() As String
            Get
                Return ResourceManager.GetString("Order_RequiredDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Order_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Freight() As String
            Get
                Return ResourceManager.GetString("Order_Freight", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipName() As String
            Get
                Return ResourceManager.GetString("Order_ShipName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipAddress() As String
            Get
                Return ResourceManager.GetString("Order_ShipAddress", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipCity() As String
            Get
                Return ResourceManager.GetString("Order_ShipCity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipRegion() As String
            Get
                Return ResourceManager.GetString("Order_ShipRegion", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipPostalCode() As String
            Get
                Return ResourceManager.GetString("Order_ShipPostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_ShipCountry() As String
            Get
                Return ResourceManager.GetString("Order_ShipCountry", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Customer() As String
            Get
                Return ResourceManager.GetString("Order_Customer", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Employee() As String
            Get
                Return ResourceManager.GetString("Order_Employee", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Shipper() As String
            Get
                Return ResourceManager.GetString("Order_Shipper", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product() As String
            Get
                Return ResourceManager.GetString("Product", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property ProductPlural() As String
            Get
                Return ResourceManager.GetString("ProductPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_ProductID() As String
            Get
                Return ResourceManager.GetString("Product_ProductID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_ProductName() As String
            Get
                Return ResourceManager.GetString("Product_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_QuantityPerUnit() As String
            Get
                Return ResourceManager.GetString("Product_QuantityPerUnit", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Product_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_UnitsInStock() As String
            Get
                Return ResourceManager.GetString("Product_UnitsInStock", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_UnitsOnOrder() As String
            Get
                Return ResourceManager.GetString("Product_UnitsOnOrder", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_ReorderLevel() As String
            Get
                Return ResourceManager.GetString("Product_ReorderLevel", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Discontinued() As String
            Get
                Return ResourceManager.GetString("Product_Discontinued", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Category() As String
            Get
                Return ResourceManager.GetString("Product_Category", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Supplier() As String
            Get
                Return ResourceManager.GetString("Product_Supplier", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Region() As String
            Get
                Return ResourceManager.GetString("Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RegionPlural() As String
            Get
                Return ResourceManager.GetString("RegionPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Region_RegionID() As String
            Get
                Return ResourceManager.GetString("Region_RegionID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Region_RegionDescription() As String
            Get
                Return ResourceManager.GetString("Region_RegionDescription", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Shipper() As String
            Get
                Return ResourceManager.GetString("Shipper", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property ShipperPlural() As String
            Get
                Return ResourceManager.GetString("ShipperPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Shipper_ShipperID() As String
            Get
                Return ResourceManager.GetString("Shipper_ShipperID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Shipper_CompanyName() As String
            Get
                Return ResourceManager.GetString("Shipper_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Shipper_Phone() As String
            Get
                Return ResourceManager.GetString("Shipper_Phone", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier() As String
            Get
                Return ResourceManager.GetString("Supplier", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property SupplierPlural() As String
            Get
                Return ResourceManager.GetString("SupplierPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_SupplierID() As String
            Get
                Return ResourceManager.GetString("Supplier_SupplierID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_CompanyName() As String
            Get
                Return ResourceManager.GetString("Supplier_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_ContactName() As String
            Get
                Return ResourceManager.GetString("Supplier_ContactName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_ContactTitle() As String
            Get
                Return ResourceManager.GetString("Supplier_ContactTitle", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_Address() As String
            Get
                Return ResourceManager.GetString("Supplier_Address", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_City() As String
            Get
                Return ResourceManager.GetString("Supplier_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_Region() As String
            Get
                Return ResourceManager.GetString("Supplier_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_PostalCode() As String
            Get
                Return ResourceManager.GetString("Supplier_PostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_Country() As String
            Get
                Return ResourceManager.GetString("Supplier_Country", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_Phone() As String
            Get
                Return ResourceManager.GetString("Supplier_Phone", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_Fax() As String
            Get
                Return ResourceManager.GetString("Supplier_Fax", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Supplier_HomePage() As String
            Get
                Return ResourceManager.GetString("Supplier_HomePage", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Territory() As String
            Get
                Return ResourceManager.GetString("Territory", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property TerritoryPlural() As String
            Get
                Return ResourceManager.GetString("TerritoryPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Territory_TerritoryID() As String
            Get
                Return ResourceManager.GetString("Territory_TerritoryID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Territory_TerritoryDescription() As String
            Get
                Return ResourceManager.GetString("Territory_TerritoryDescription", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Territory_Region() As String
            Get
                Return ResourceManager.GetString("Territory_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_productPlural() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_productPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_ProductID() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_ProductID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_ProductName() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_SupplierID() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_SupplierID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_CategoryID() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_CategoryID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_QuantityPerUnit() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_QuantityPerUnit", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_UnitsInStock() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_UnitsInStock", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_UnitsOnOrder() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_UnitsOnOrder", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_ReorderLevel() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_ReorderLevel", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_Discontinued() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_Discontinued", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Alphabetical_list_of_product_CategoryName() As String
            Get
                Return ResourceManager.GetString("Alphabetical_list_of_product_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Sales_for_1997() As String
            Get
                Return ResourceManager.GetString("Category_Sales_for_1997", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Sales_for_1997Plural() As String
            Get
                Return ResourceManager.GetString("Category_Sales_for_1997Plural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Sales_for_1997_CategoryName() As String
            Get
                Return ResourceManager.GetString("Category_Sales_for_1997_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Category_Sales_for_1997_CategorySales() As String
            Get
                Return ResourceManager.GetString("Category_Sales_for_1997_CategorySales", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Current_Product_List() As String
            Get
                Return ResourceManager.GetString("Current_Product_List", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Current_Product_ListPlural() As String
            Get
                Return ResourceManager.GetString("Current_Product_ListPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Current_Product_List_ProductID() As String
            Get
                Return ResourceManager.GetString("Current_Product_List_ProductID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Current_Product_List_ProductName() As String
            Get
                Return ResourceManager.GetString("Current_Product_List_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_City() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_CityPlural() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_CityPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_City_City() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_City_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_City_CompanyName() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_City_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_City_ContactName() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_City_ContactName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Customer_and_Suppliers_by_City_Relationship() As String
            Get
                Return ResourceManager.GetString("Customer_and_Suppliers_by_City_Relationship", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice() As String
            Get
                Return ResourceManager.GetString("Invoice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property InvoicePlural() As String
            Get
                Return ResourceManager.GetString("InvoicePlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipName() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipAddress() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipAddress", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipCity() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipCity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipRegion() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipRegion", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipPostalCode() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipPostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipCountry() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipCountry", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_CustomerID() As String
            Get
                Return ResourceManager.GetString("Invoice_CustomerID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_CustomerName() As String
            Get
                Return ResourceManager.GetString("Invoice_CustomerName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Address() As String
            Get
                Return ResourceManager.GetString("Invoice_Address", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_City() As String
            Get
                Return ResourceManager.GetString("Invoice_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Region() As String
            Get
                Return ResourceManager.GetString("Invoice_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_PostalCode() As String
            Get
                Return ResourceManager.GetString("Invoice_PostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Country() As String
            Get
                Return ResourceManager.GetString("Invoice_Country", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Salesperson() As String
            Get
                Return ResourceManager.GetString("Invoice_Salesperson", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_OrderID() As String
            Get
                Return ResourceManager.GetString("Invoice_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_OrderDate() As String
            Get
                Return ResourceManager.GetString("Invoice_OrderDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_RequiredDate() As String
            Get
                Return ResourceManager.GetString("Invoice_RequiredDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Invoice_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ShipperName() As String
            Get
                Return ResourceManager.GetString("Invoice_ShipperName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ProductID() As String
            Get
                Return ResourceManager.GetString("Invoice_ProductID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ProductName() As String
            Get
                Return ResourceManager.GetString("Invoice_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Invoice_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Quantity() As String
            Get
                Return ResourceManager.GetString("Invoice_Quantity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Discount() As String
            Get
                Return ResourceManager.GetString("Invoice_Discount", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_ExtendedPrice() As String
            Get
                Return ResourceManager.GetString("Invoice_ExtendedPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Invoice_Freight() As String
            Get
                Return ResourceManager.GetString("Invoice_Freight", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_ExtendedPlural() As String
            Get
                Return ResourceManager.GetString("Order_Details_ExtendedPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_OrderID() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_ProductID() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_ProductID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_ProductName() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_Quantity() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_Quantity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_Discount() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_Discount", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Details_Extended_ExtendedPrice() As String
            Get
                Return ResourceManager.GetString("Order_Details_Extended_ExtendedPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Subtotal() As String
            Get
                Return ResourceManager.GetString("Order_Subtotal", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_SubtotalPlural() As String
            Get
                Return ResourceManager.GetString("Order_SubtotalPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Subtotal_OrderID() As String
            Get
                Return ResourceManager.GetString("Order_Subtotal_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Order_Subtotal_Subtotal() As String
            Get
                Return ResourceManager.GetString("Order_Subtotal_Subtotal", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry() As String
            Get
                Return ResourceManager.GetString("Orders_Qry", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_QryPlural() As String
            Get
                Return ResourceManager.GetString("Orders_QryPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_OrderID() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_CustomerID() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_CustomerID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_EmployeeID() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_EmployeeID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_OrderDate() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_OrderDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_RequiredDate() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_RequiredDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipVia() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipVia", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_Freight() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_Freight", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipName() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipAddress() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipAddress", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipCity() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipCity", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipRegion() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipRegion", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipPostalCode() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipPostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_ShipCountry() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_ShipCountry", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_CompanyName() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_Address() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_Address", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_City() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_City", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_Region() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_Region", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_PostalCode() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_PostalCode", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Orders_Qry_Country() As String
            Get
                Return ResourceManager.GetString("Orders_Qry_Country", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Sales_for_1997() As String
            Get
                Return ResourceManager.GetString("Product_Sales_for_1997", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Sales_for_1997Plural() As String
            Get
                Return ResourceManager.GetString("Product_Sales_for_1997Plural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Sales_for_1997_CategoryName() As String
            Get
                Return ResourceManager.GetString("Product_Sales_for_1997_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Sales_for_1997_ProductName() As String
            Get
                Return ResourceManager.GetString("Product_Sales_for_1997_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Product_Sales_for_1997_ProductSales() As String
            Get
                Return ResourceManager.GetString("Product_Sales_for_1997_ProductSales", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_Above_Average_Price() As String
            Get
                Return ResourceManager.GetString("Products_Above_Average_Price", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_Above_Average_PricePlural() As String
            Get
                Return ResourceManager.GetString("Products_Above_Average_PricePlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_Above_Average_Price_ProductName() As String
            Get
                Return ResourceManager.GetString("Products_Above_Average_Price_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_Above_Average_Price_UnitPrice() As String
            Get
                Return ResourceManager.GetString("Products_Above_Average_Price_UnitPrice", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category() As String
            Get
                Return ResourceManager.GetString("Products_by_Category", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_CategoryPlural() As String
            Get
                Return ResourceManager.GetString("Products_by_CategoryPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category_CategoryName() As String
            Get
                Return ResourceManager.GetString("Products_by_Category_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category_ProductName() As String
            Get
                Return ResourceManager.GetString("Products_by_Category_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category_QuantityPerUnit() As String
            Get
                Return ResourceManager.GetString("Products_by_Category_QuantityPerUnit", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category_UnitsInStock() As String
            Get
                Return ResourceManager.GetString("Products_by_Category_UnitsInStock", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Products_by_Category_Discontinued() As String
            Get
                Return ResourceManager.GetString("Products_by_Category_Discontinued", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_Category() As String
            Get
                Return ResourceManager.GetString("Sales_by_Category", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_CategoryPlural() As String
            Get
                Return ResourceManager.GetString("Sales_by_CategoryPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_Category_CategoryID() As String
            Get
                Return ResourceManager.GetString("Sales_by_Category_CategoryID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_Category_CategoryName() As String
            Get
                Return ResourceManager.GetString("Sales_by_Category_CategoryName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_Category_ProductName() As String
            Get
                Return ResourceManager.GetString("Sales_by_Category_ProductName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_by_Category_ProductSales() As String
            Get
                Return ResourceManager.GetString("Sales_by_Category_ProductSales", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_Amount() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_Amount", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_AmountPlural() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_AmountPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_Amount_SaleAmount() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_Amount_SaleAmount", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_Amount_OrderID() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_Amount_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_Amount_CompanyName() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_Amount_CompanyName", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Sales_Totals_by_Amount_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Sales_Totals_by_Amount_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Quarter() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Quarter", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_QuarterPlural() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_QuarterPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Quarter_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Quarter_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Quarter_OrderID() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Quarter_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Quarter_Subtotal() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Quarter_Subtotal", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Year() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Year", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_YearPlural() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_YearPlural", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Year_ShippedDate() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Year_ShippedDate", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Year_OrderID() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Year_OrderID", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Summary_of_Sales_by_Year_Subtotal() As String
            Get
                Return ResourceManager.GetString("Summary_of_Sales_by_Year_Subtotal", resourceCulture)
            End Get
        End Property
	
    End Class
End Namespace
