'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Public Class ViewResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scaffolding.DatabaseFirst.VB.ViewResources", GetType(ViewResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

					Public Shared ReadOnly Property Command_New() As String
            Get
                Return ResourceManager.GetString("Command_New", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Edit() As String
            Get
                Return ResourceManager.GetString("Command_Edit", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Delete() As String
            Get
                Return ResourceManager.GetString("Command_Delete", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Refresh() As String
            Get
                Return ResourceManager.GetString("Command_Refresh", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Reports() As String
            Get
                Return ResourceManager.GetString("Command_Reports", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Add() As String
            Get
                Return ResourceManager.GetString("Command_Add", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Save() As String
            Get
                Return ResourceManager.GetString("Command_Save", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_SaveAndClose() As String
            Get
                Return ResourceManager.GetString("Command_SaveAndClose", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_SaveAndNew() As String
            Get
                Return ResourceManager.GetString("Command_SaveAndNew", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Reset() As String
            Get
                Return ResourceManager.GetString("Command_Reset", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_SaveAll() As String
            Get
                Return ResourceManager.GetString("Command_SaveAll", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Close() As String
            Get
                Return ResourceManager.GetString("Command_Close", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_Count() As String
            Get
                Return ResourceManager.GetString("Command_Count", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_CustomizeLayout() As String
            Get
                Return ResourceManager.GetString("Command_CustomizeLayout", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_SaveLayout() As String
            Get
                Return ResourceManager.GetString("Command_SaveLayout", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property Command_ResetLayout() As String
            Get
                Return ResourceManager.GetString("Command_ResetLayout", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RibbonPage_Home() As String
            Get
                Return ResourceManager.GetString("RibbonPage_Home", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RibbonPage_View() As String
            Get
                Return ResourceManager.GetString("RibbonPage_View", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RibbonPageGroup_Tasks() As String
            Get
                Return ResourceManager.GetString("RibbonPageGroup_Tasks", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RibbonPageGroup_Layout() As String
            Get
                Return ResourceManager.GetString("RibbonPageGroup_Layout", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property RibbonPageGroup_Appearance() As String
            Get
                Return ResourceManager.GetString("RibbonPageGroup_Appearance", resourceCulture)
            End Get
        End Property
				Public Shared ReadOnly Property LayoutPanel_Navigation() As String
            Get
                Return ResourceManager.GetString("LayoutPanel_Navigation", resourceCulture)
            End Get
        End Property
	
    End Class
End Namespace
